namespace: "ebeyond"
name: "ans-minio"
version: "1.0.12"
readme: "README.md"
authors:
    - "Marc Ende <me@e-beyond.de>"
license:
    - "MIT"
tags:
    - minio
    - s3
    - storage
    - server
repository: "https://www.github.com/oss4u/ans-minio"